### ISSUE TITLE
训练完最后一个epoch，测试存在问题

### ISSUE THREAD

**Issue by eeric** [deepcam-cn/yolov5-face#11]
比如训练250轮，结束后会进行测试，在test.py里面第180，181行：
180th lines
if plots:                    
confusion_matrix.process_batch(pred, torch.cat((labels[:, 0:1], tbox), 1))
存在问题是：
utils/metrics.py", line 146, in process_batch
    self.matrix[gc, detection_classes[m1[j]]] += 1  # correct
IndexError: index 3 is out of bounds for axis 1 with size 2

我把180th,181th行注释掉，就可以测试和保存最后1个epoch的模型了。

**Comment by CompliceU** [comment]
@derronqi 我训练完20代之后，验证部分一直报显存溢出，不知道从哪个地方可以调整验证测试时的显存使用情况呢，非常感谢

**Comment by CompliceU** [comment]
@derronqi 你好，非常感谢你的工作，我这边训练完20代的时候开始验证测试模型，但是在NMS部分总是报显存溢出的问题，不知道从哪可以调整显存溢出的问题，非常感谢
