### ISSUE TITLE
FlOPs计算方式

### ISSUE THREAD

**Issue by violet2422** [deepcam-cn/yolov5-face#114]
请问论文中的FLOPs是怎么得到的，为什么和官方YOLOv5相差这么大，我尝试将FOCUS层换位论文中的STEM层，计算复杂度依然相差很大？
![image](https://user-images.githubusercontent.com/73391269/147895629-9938b4a6-30b7-4b71-b467-a5225eca14e1.png)
![image](https://user-images.githubusercontent.com/73391269/147895631-92bd9b8e-ab8e-4ab0-af54-5947f89c2b89.png)

**Comment by derronqi** [comment]
输入大小和计算方式不一样，yolov5-face用的是thop

**Comment by Monkey-D-Luffy-star** [comment]
@violet2422 你找出哪里差距比较大了吗，我也不明白为什么这里的FLOPs降了这么多
