### ISSUE TITLE
jetson  TX2  tensorrt 

### ISSUE THREAD

**Issue by Programmerwyl** [deepcam-cn/yolov5-face#128]
tensorrt  version: 7.1.3

onnx  to   tensorrt
way: trtexec and  code

code is as attached.

the detected result is wrong.

![result](https://user-images.githubusercontent.com/22095854/151321302-6599f958-d4b8-4834-ba90-a0b2624a88b4.jpg)

**Comment by bobo0810** [comment]
Is that why I asked for version 8.2

**Comment by Programmerwyl** [comment]
Supported or not  tensorrt 8.0 ?
The latest update is 8.0 for sdkmanager.

**Comment by Programmerwyl** [comment]
At present, the latest sdkmager comes with tensorrt 8.0 version, I want to know if it supports？
thanks.

**Comment by bobo0810** [comment]
> At present, the latest sdkmager comes with tensorrt 8.0 version, I want to know if it supports？ thanks.

I haven't tested it. Looking forward to your feedback~

**Comment by Programmerwyl** [comment]
ok, thanks .
I'll get back when I'm done testing.

**Comment by Programmerwyl** [comment]
tensorrt version: 8.0.1.6,it is ok.

**Comment by lpkoh** [comment]
Hi, wondering if possible to fix this for Tensorrt 7.1.3, or must I upgrade to Tensorrt 8?

**Comment by yukaizhou** [comment]
> 
Is this problem solved? I also wonder why is it version related?
