### ISSUE TITLE
conf

### ISSUE THREAD

**Issue by SongHfei** [deepcam-cn/yolov5-face#138]

**Comment by SongHfei** [comment]
为什么拿自己的数据 训练出来的结果  人脸检测 的 置信度偏低呢？很少有0.99以上的conf

**Comment by derronqi** [comment]
为啥要0.99？看下ap不就可以了，分数有啥意义

**Comment by SongHfei** [comment]
> 为啥要.99？看下ap不就可以了，0有啥意义

因为检测 到识别过程，其它模块 会根据这个人脸框置信度 剔除掉一部分人脸。
比如检测对齐时会根据情况 去除掉置信度0.85下的人脸。

**Comment by derronqi** [comment]
好好理解下ap的意义
