### ISSUE TITLE
test_widerface.py   where is the file wider_val.txt?

### ISSUE THREAD

**Issue by aa12356jm** [deepcam-cn/yolov5-face#141]
parser.add_argument('--folder_pict', default='/yolov5-face/data/widerface/val/wider_val.txt', type=str, help='folder_pict')  how to get the file wider_val.txt? thanks

**Comment by mahdis-sa** [comment]
I have the same issue :(
did you find it?

**Comment by mahdis-sa** [comment]
@aa12356jm did you find out the wider_val.txt ?

**Comment by derronqi** [comment]
just file list

**Comment by mahdis-sa** [comment]
@derronqi 
sorry, could you please tell us which file list you mean?
based on your latest update validation data-name saved like 1.jpg, 2.jpg and etc. after data preparation. so you mean the file list of original validation data or the saved one? 
could you please paste one line of your file list here? then we can get it easier.

**Comment by zuofengyouliang** [comment]
i have the same questions

**Comment by zuofengyouliang** [comment]
> @derronqi sorry, could you please tell us which file list you mean? based on your latest update validation data-name saved like 1.jpg, 2.jpg and etc. after data preparation. so you mean the file list of original validation data or the saved one? could you please paste one line of your file list here? then we can get it easier.

did you find out the .txt?

**Comment by mahdis-sa** [comment]
@zuofengyouliang unfortunately not

**Comment by derronqi** [comment]
find <dir> -name *.jpg > imagelist.txt
