### ISSUE TITLE
'Upsample' object has no attribute 'recompute_scale_factor'

### ISSUE THREAD

**Issue by Lance-Owen** [deepcam-cn/yolov5-face#144]
torch1.11 yolov5

**Comment by MyraBaba** [comment]
@bobo0810 

Same problem on cpu 

detect_face.py
AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'

**Comment by MyraBaba** [comment]
downgrade to 10.0 solved my problem. 

version is THE problem preceding the Global Warming I assume.
