### ISSUE TITLE
Align Landmar

### ISSUE THREAD

**Issue by MyraBaba** [deepcam-cn/yolov5-face#145]
Hi,

By the way have you 112x112 align version or utils somewhere ? 

O can we use retinafaces align . Is the Landmark [5 point] is in same order  as in retinaface?

**Comment by derronqi** [comment]
yes

**Comment by MyraBaba** [comment]
@derronqi  It very good and fast.

One last question . have you any practical experience for removing the blury and bad faces after detection. to improve recg. quality?

**Comment by derronqi** [comment]
https://github.com/deepcam-cn/FaceQuality

**Comment by MyraBaba** [comment]
Couldnt see pertained model of that one. Do you know where we can find
