### ISSUE TITLE
推理速度比较慢，与其计算量Flops不太匹配

### ISSUE THREAD

**Issue by zhongwenkun886** [deepcam-cn/yolov5-face#146]
在PC端和移动端都基于ncnn推理，以及移动端基于TFlite-GPU推理，Flops相近的两个模型 yolov5n-0.5 和 SCRFD-0.5GF(Arxiv21)，网络输入的图像数据的归一化分辨率也一样，但 yolov5n-0.5要慢很多。在一加5手机上基于TFlite-GPU，输入归一化分辨率640*480， yolov5n-0.5推理一次要100多ms，而 SCRFD-0.5GF(Arxiv21)只需要20多ms。
何解？谢谢。

**Comment by derronqi** [comment]
https://github.com/FeiGeChuanShu/ncnn_Android_face/tree/main/ncnn-android-yolov5_face
