### ISSUE TITLE
about some detals

### ISSUE THREAD

**Issue by www516717402** [deepcam-cn/yolov5-face#17]
Thank you for open this repo. I have some questions as follows:
1. All model use **800** image size for input in readme.md table ? However 640 images size in evaluate ?
https://github.com/deepcam-cn/yolov5-face/blob/f4db424d7066ca30b32d81cac634ec846e2b0c5f/train.py#L439

2. Have you mean filter small face by this code? Anything else?
> As we explain before, the Mosaic has to work with the ignoring small faces, otherwise the performance degrades dramatically

https://github.com/deepcam-cn/yolov5-face/blob/f4db424d7066ca30b32d81cac634ec846e2b0c5f/utils/datasets.py#L900

**Comment by derronqi** [comment]
1、p5 800, p6 832, widerface test 640
2、no, check the train2val.py
