### ISSUE TITLE
no face detected TensorRT

### ISSUE THREAD

**Issue by quocnhat** [deepcam-cn/yolov5-face#180]
Hi, @bobo0810   Really appreciate your works!
I've successfully run all the command line in your readme file. But the resulting image detects no face. 
What am I doing wrong?  Is that cause of a different TensorRT version? My TensorRT version is 8.0.0.3
Thank you!

python torch2trt/main.py  --trt_path pretrained/yolov5s-face.trt 
[TensorRT] INFO: [MemUsageChange] Init CUDA: CPU +136, GPU +0, now: CPU 259, GPU 407 (MiB)
[TensorRT] INFO: Loaded engine size: 50 MB
[TensorRT] INFO: [MemUsageSnapshot] deserializeCudaEngine begin: CPU 259 MiB, GPU 407 MiB
[TensorRT] WARNING: TensorRT was linked against cuBLAS/cuBLAS LT 11.4.2 but loaded cuBLAS/cuBLAS LT 11.4.1
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +184, GPU +76, now: CPU 455, GPU 527 (MiB)
[TensorRT] INFO: [MemUsageChange] Init cuDNN: CPU +110, GPU +46, now: CPU 565, GPU 573 (MiB)
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 565, GPU 555 (MiB)
[TensorRT] INFO: [MemUsageSnapshot] deserializeCudaEngine end: CPU 565 MiB, GPU 555 MiB
[TensorRT] WARNING: TensorRT was linked against cuBLAS/cuBLAS LT 11.4.2 but loaded cuBLAS/cuBLAS LT 11.4.1
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +10, now: CPU 565, GPU 565 (MiB)
[TensorRT] INFO: [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 565, GPU 573 (MiB)
bingding: input (1, 3, 640, 640)
bingding: output (1, 25200, 16)
img.shape:  torch.Size([1, 3, 640, 640])
orgimg.shape:  (768, 1024, 3)
result save in {...}yolov5-face/torch2trt/result.jpg
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 688, GPU 785 (MiB)

**Comment by bobo0810** [comment]
Try version 8.2
1. Previous experiments: version differences have a greater impact on the results.
2. Breakpoint debugging is recommended to locate problems.

**Comment by quocnhat** [comment]
Thank you for quick answer. I'll give feedback after testing.

**Comment by quocnhat** [comment]
Error on drawing bboxes rectangle. Thanks!

**Comment by Monkey-D-Luffy-star** [comment]
> Error on drawing bboxes rectangle. Thanks!

I'm having the same problem. Where did you change it, please?

**Comment by quocnhat** [comment]
Sorry I can not check it now, Can you please take a look at function https://github.com/deepcam-cn/yolov5-face/blob/master/utils/plots.py#:~:text=def%20plot_one_box(x%2C%20img%2C%20color%3DNone%2C%20label%3DNone%2C%20line_thickness%3DNone)%3A  . My issue comes from there

**Comment by zts2002** [comment]
i have the same problem sir, can you show me the right one code of main.py? thanks!
