### ISSUE TITLE
Test Error

### ISSUE THREAD

**Issue by razvan-tanase** [deepcam-cn/yolov5-face#185]
Hi guys,

I tried to use the WIDERface evaluation today with the following command:
python .\test_widerface.py --weights 'yolov5s' --dataset_folder [my-path]

but I get this error:  
Traceback (most recent call last):
  File "C:\YOLOv5\yolov5-face\test_widerface.py", line 135, in <module>
    with open(opt.folder_pict, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/yolov5-face/data/widerface/val/wider_val.txt'

Indeed, I don't have that file specified in the default path. In the 'data' folder there is no 'widerface' subfolder and my question is:
How I'm supposed to fix this considering the fact that I don't want to retrain a new model and just to use a pre-trained weight. In other words, I don't want to download the dataset from WIDER.

**Comment by Ds-noman** [comment]
@razvan-tanase how did you solve this error ?
