### ISSUE TITLE
Yolov7-face

### ISSUE THREAD

**Issue by gyupro** [deepcam-cn/yolov5-face#198]
HI,

I just saw your release note. I was wondering if you are willing to release the weight of yolov7-face that you trained.

and what dataset have you trained on? is it just trained with widerface-dataset or more of that? 

I found your excellent work and it beats most detectors. Thank you for your work.

**Comment by aviadmx** [comment]
Would also like, could be really useful.  
Also what type of V7 did you use, the official or non-official one?

**Comment by derronqi** [comment]
update soon
