### ISSUE TITLE
Train

### ISSUE THREAD

**Issue by SwordX** [deepcam-cn/yolov5-face#20]
你好，我在运行了val2yolo.py的代码后进行训练，出现如下问题：

**Comment by SwordX** [comment]
WARNING: Ignoring corrupted image and/or lable xxxxxxxx.jpg:non-normalized or out of bounds coeedinate labels

**Comment by spikyknox** [comment]
I also find an error. In the suggested annotation the format is  Left,Top,Right,Bot and yolo expect cx,cy, w,y . So I had to convert in train2yolo to :
`            annotation[0, 0] = ((label[0] + label[2]) / 2) / width  # cx
            annotation[0, 1] = ((label[1] + label[3]) / 2) / height  # cy
            annotation[0, 2] = (label[2]-label[0]) / width  # w
            annotation[0, 3] = (label[3]-label[1]) / height  # h
`

**Comment by SwordX** [comment]
And a new Error:
No results.txt files found in ......../runs/train/exp

**Comment by SwordX** [comment]
and can't  save weight file

**Comment by derronqi** [comment]
training more than 20 epochs
