### ISSUE TITLE
how do you get the detected result of test.jpg in readme. hope your reply

### ISSUE THREAD

**Issue by ReverseSystem001** [deepcam-cn/yolov5-face#231]
when i run :     python3 detect_face.py --weights ./yolov5l-face.pt --source ./data/images/test.jpg with
    img_size = 640
    conf_thres = 0.3
    #conf_thres = 0.6
    iou_thres = 0.5
there are only  227 faces detected. 
how do you get the Test detect Picture result in readme. the following pic is my result. 
![test](https://user-images.githubusercontent.com/23073337/209750985-29e27d6f-e3ab-460e-b5d8-1cd4bc44e38f.jpg)

hope your reply

**Comment by derronqi** [comment]
test image size 2048

**Comment by ReverseSystem001** [comment]
get it. Thanks for you reply.
