### ISSUE TITLE
unable to download from baidu

### ISSUE THREAD

**Issue by iperov** [deepcam-cn/yolov5-face#24]
can you please share the weights in other cloud?

**Comment by fortminors** [comment]
There's  a script to download all the weights. it's called download_weights.sh

**Comment by iperov** [comment]
script will not help, because china restricts to download from other countries

**Comment by iperov** [comment]
but weights from https://github.com/ultralytics/yolov5/releases are not yolov5face weights.

**Comment by fortminors** [comment]
I see what you mean now, that's true. Have you tried using VPN for downloading?

**Comment by iperov** [comment]
nevermind
the weights have been published on google drive

**Comment by fortminors** [comment]
@iperov where did you find it? I can only find the small model weights on google drive

**Comment by iperov** [comment]
small model is enough for me.

**Comment by iperov** [comment]
I can ask china friend to download from baidu. But first I want to test the model.

**Comment by iperov** [comment]
I am satisfied with yolov5s. Faster and better than S3FD.
Will add it to DeepFaceLive.

**Comment by iperov** [comment]
you can grab ready to use onnx YoloV5Face from my repo https://github.com/iperov/DeepFaceLive/tree/master/modelhub/onnx/YoloV5Face

**Comment by fortminors** [comment]
@iperov Yes I’ve seen your work, looks amazing! Thanks :)
