### ISSUE TITLE
train2yolo

### ISSUE THREAD

**Issue by SwordX** [deepcam-cn/yolov5-face#25]
现在下载的标签是labelv2.txt，修改代码后（代码只修改了路径），下载后运行train2yolo.py等文件进行训练后似乎有标签无法对齐的问题，如图片所示
![train_batch0](https://user-images.githubusercontent.com/30286711/120475867-7f3f2c00-c3dc-11eb-86b9-1e8e73224d7d.jpg)

**Comment by gouravvemula0** [comment]
same for me i too got similar output

**Comment by derronqi** [comment]
sorry, I updated annotation files.

**Comment by SwordX** [comment]
Thank you

**Comment by SwordX** [comment]
现在正常训练了，感谢您的帮助。但是在trian/exp中的train_batch.jpg中会有许多人脸没有被正确框选到，会影响训练吗（如图所示）
![train_batch0](https://user-images.githubusercontent.com/30286711/120595911-af86d900-c475-11eb-8ec4-15fb17f72cbe.jpg)
