### ISSUE TITLE
Inference Speed

### ISSUE THREAD

**Issue by LeeKyungwook** [deepcam-cn/yolov5-face#28]
Thanks for sharing gread code.

I have a question about yolov5-face inference speed.
Yolov5-face is more accurate than scrfd, but inference speed is more slower.

Is it true?

**Comment by derronqi** [comment]
no, we test scrfd-0.5gf and yolov5n-0.5 android app,nearly the same speed.

**Comment by LeeKyungwook** [comment]
how about cpu in single thread?

**Comment by derronqi** [comment]
could you have a test and then share your result.

**Comment by LeeKyungwook** [comment]
I tested it.

Env : cpu i7-8700, single thread
SCRFD_0.5G : 25ms
yolov5n-0.5 : 60ms

could you share your test result?
