### ISSUE TITLE
大人脸检测出错 

### ISSUE THREAD

**Issue by carfei** [deepcam-cn/yolov5-face#38]
当单张人脸面积较大时，几乎完全出错。要么会检测到多张人脸，要么无法检测到。现在的人脸检测越来越注重小人脸检测，却无法精确的检测大人脸

**Comment by derronqi** [comment]
这个跟训练集有关，你可以换其他数据集训练

**Comment by derronqi** [comment]
我更新了一个新的训练集，解决大人脸检测的问题
