### ISSUE TITLE
统计的Flops不一样

### ISSUE THREAD

**Issue by ppogg** [deepcam-cn/yolov5-face#39]
大佬您好，好像你readme中统计的flops和我用yolov5统计出来的不一样：
yolov5-n：Model Summary: 308 layers, 1705462 parameters, 1705462 gradients, 5.0 GFLOPS
yolov5-0.5n：Model Summary: 308 layers, 439734 parameters, 439734 gradients, 1.4 GFLOPS

**Comment by derronqi** [comment]
使用VGA分辨率统计的计算量

**Comment by pengtougu** [comment]
请问有相关链接吗大佬，我想看看如何计算

**Comment by derronqi** [comment]
代码中有
