### ISSUE TITLE
转换为onnx文件时出错

### ISSUE THREAD

**Issue by HaojieYuu** [deepcam-cn/yolov5-face#4]
您好，在使用models/export.py将训练好的yolov5s-face.pt转换为onnx文件时，报错如下：
RuntimeError: step!=1 is currently not supported
请问您有什么解决的方法么？谢谢！

**Comment by derronqi** [comment]
确认下是不是版本的问题，或者参考这个：https://github.com/hpc203/yolov5-face-landmarks-opencv
