### ISSUE TITLE
训练时验证显存溢出

### ISSUE THREAD

**Issue by CompliceU** [deepcam-cn/yolov5-face#42]
@derronqi  每次训练一代结束后，进行验证和模型测试时，显存会溢出，不知道是什么原因，我batch_size设置的很小也会出现这个问题。不知道你是否也出现了这样的情况，谢谢
![image](https://user-images.githubusercontent.com/24600457/129871273-c85b3b19-a98b-42b7-acd0-9675be365f76.png)

**Comment by derronqi** [comment]
不会呢

**Comment by CompliceU** [comment]
@derronqi 好吧，但是确实在这个验证测试计算指标的时候会占用训练还大的显存，而且比训练的也慢，不知道大佬有啥办法可以改进的吗

**Comment by CompliceU** [comment]
我发现是因为作者在NMS中可能是希望获得更好的效果去掉了框的最大数约束，导致预测的产生的框全部参与NMS计算，使得显存在验证测试时大幅变化，时间变长。

**Comment by derronqi** [comment]
20个epoch后才进行验证，那时候框收敛的差不多了
