### ISSUE TITLE
多类别人脸，只能检测出来第一种人脸？

### ISSUE THREAD

**Issue by changhy666** [deepcam-cn/yolov5-face#45]
你好，我用这个代码跑3中类别人脸检测遇到了一点问题，多个类别训练完，跑检测脚本，只能预测出来第一个类别（人脸框，landm都正常），另外两个类别的人脸预测不出来，把过nms前，原始pred的tensor打印出来看，发现后两列被固定成0。然后检查了训练代码，发现另外两个类别的分类score和obj的score都是正常的，训练过程中的precision和recall指标都很低，不知道是不是跟nms超时10s有关。调试了很久找不到原因，可以帮忙分析下吗？谢谢。
hello, this is my question: train 3 class faces by this code, but when i run detect_face.py to pred a picture, only the 0 class can be success detected，the pred tensor of the other class faces  always be 0.00000e+00. i checked the train.py, i also find the question, that is precision and recall is too low, but the pred tensor is ok in score of the other class face.

**Comment by changhy666** [comment]
![image](https://user-images.githubusercontent.com/57101883/130721110-f8d44eb6-7d5d-4d03-b3b4-a3b0c3162b6b.png)

**Comment by Teeemio** [comment]
你可以看一下yolo.py里的67行左右y[..., [0,1,2,3,4,15]] = x[i][..., [0,1,2,3,4,15]].sigmoid()
这里作者手动写了需要做sigmoid的位置，其中最后的15是对第一类的计算，如果你想增加类别可以考虑加入16，17。
(我也调试了好久绝了。)

**Comment by changhy666** [comment]
> 你可以看一下yolo.py里的67行左右y[..., [0,1,2,3,4,15]] = x[i][..., [0,1,2,3,4,15]].sigmoid()
> 这里作者手动写了需要做sigmoid的位置，其中最后的15是对第一类的计算，如果你想增加类别可以考虑加入16，17。
> (我也调试了好久绝了。)

**Comment by changhy666** [comment]
> 你可以看一下yolo.py里的67行左右y[..., [0,1,2,3,4,15]] = x[i][..., [0,1,2,3,4,15]].sigmoid()
> 这里作者手动写了需要做sigmoid的位置，其中最后的15是对第一类的计算，如果你想增加类别可以考虑加入16，17。
> (我也调试了好久绝了。)

感谢git友，救了我的老命了！！！！

**Comment by sandinhand** [comment]
我在做这个改成二个类别识别的时候一直会有个   RuntimeError: The size of tensor a (48) must match the size of tensor b (51) at non-singleton dimension 0 错误，这是什么原因造成的呢

**Comment by nobody-cheng** [comment]
> 你好，我用这个代码跑3中类别人脸检测遇到了一点问题，多个类别训练完，跑检测脚本，只能预测出来第一个类别（人脸框，landm都正常），另外两个类别的人脸预测不出来，把过nms前，原始pred的tensor打印出来看，发现后两列被固定成0。然后检查了训练代码，发现另外两个类别的分类score和obj的score都是正常的，训练过程中的precision和recall指标都很低，不知道是不是跟nms超时10s有关。调试了很久找不到原因，可以帮忙分析下吗？谢谢。 hello, this is my question: train 3 class faces by this code, but when i run detect_face.py to pred a picture, only the 0 class can be success detected，the pred tensor of the other class faces always be 0.00000e+00. i checked the train.py, i also find the question, that is precision and recall is too low, but the pred tensor is ok in score of the other class face.

请问在哪里修改变成可以训练人脸，又可以检测人体

**Comment by changhy666** [comment]
首先需要加一个人体的类别的数据，5个关键点置为-1就好，因为目前代码的通用性不是太好，相关的地方比如输出shape要增加一个，切片位置也要改成你当前类别数，比如如果有三个类别那么输出就是conf1+box4+landm10+cls_score3



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年07月08日 18:10 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [deepcam-cn/yolov5-face] 多类别人脸，只能检测出来第一种人脸？ (#45) |

你好，我用这个代码跑3中类别人脸检测遇到了一点问题，多个类别训练完，跑检测脚本，只能预测出来第一个类别（人脸框，landm都正常），另外两个类别的人脸预测不出来，把过nms前，原始pred的tensor打印出来看，发现后两列被固定成0。然后检查了训练代码，发现另外两个类别的分类score和obj的score都是正常的，训练过程中的precision和recall指标都很低，不知道是不是跟nms超时10s有关。调试了很久找不到原因，可以帮忙分析下吗？谢谢。 hello, this is my question: train 3 class faces by this code, but when i run detect_face.py to pred a picture, only the 0 class can be success detected，the pred tensor of the other class faces always be 0.00000e+00. i checked the train.py, i also find the question, that is precision and recall is too low, but the pred tensor is ok in score of the other class face.

请问在哪里修改变成可以训练人脸，又可以检测人体

**Comment by qxkkk** [comment]
> 我在做这个改成二个类别识别的时候一直会有个 RuntimeError: The size of tensor a (48) must match the size of tensor b (51) at non-singleton dimension 0 错误，这是什么原因造成的呢

在代码train.py 144-148行，如果使用的预训练模型是单类别的，这里会load单类别的optimizer，导致二类别时出错，将这里注释掉就好。
```
if pretrained:
        # Optimizer
        if ckpt['optimizer'] is not None:
            optimizer.load_state_dict(ckpt['optimizer'])
            best_fitness = ckpt['best_fitness']
```

**Comment by XhHello** [comment]
> 大佬，如何给人体类的标注文件后面添加上-1啊。还有除了您说的这几处需要修改的地方，还需要修改哪些py文件的代码啊，感谢

**Comment by XhHello** [comment]
> 你可以看一下yolo.py里的67行左右y[..., [0,1,2,3,4,15]] = x[i][..., [0,1,2,3,4,15]].sigmoid() 这里作者手动写了需要做sigmoid的位置，其中最后的15是对第一类的计算，如果你想增加类别可以考虑加入16，17。 (我也调试了好久绝了。)

请问如何修改yolov5-face， 变成可以检测人脸和关键点，又可以检测人体

**Comment by XhHello** [comment]
> 请问如何修改yolov5-face， 变成可以检测人脸和关键点，又可以检测人体

您好，我想在检测人脸类和关键点的基础上，添加一个人体类检测（只要框），请问该修改代码里的哪些地方呢

**Comment by changhy666** [comment]
检测人体不用改什么吧，标注的时候把人体标进去就行了，如果想区分人体和人脸算不同类别，顶多加个分类就好。
















在 2023-04-13 10:15:13，"XhHello" ***@***.***> 写道：

请问如何修改yolov5-face， 变成可以检测人脸和关键点，又可以检测人体

您好，我想在检测人脸类和关键点的基础上，添加一个人体类检测（只要框），请问该修改代码里的哪些地方呢

**Comment by XhHello** [comment]
> 检测人体不用改什么吧，标注的时候把人体标进去就行了，如果想区分人体和人脸算不同类别，顶多加个分类就好。 在 2023-04-13 10:15:13，"XhHello" ***@***.***> 写道： 请问如何修改yolov5-face， 变成可以检测人脸和关键点，又可以检测人体 您好，我想在检测人脸类和关键点的基础上，添加一个人体类检测（只要框），请问该修改代码里的哪些地方呢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

谢谢大佬指教，您说的“顶多加个分类”是啥意思啊，我现在的数据集就是两个类别（person、face）+关键点，相比于yolov5-face增加了一个person类，是否需要修改dataset.py的数据加载代码和loss.py中的损失函数，以及检测头的输出数据维度。
我的label文件格式是这样的，person类只有框，face类有框有关键点：
0  0.8037109375 0.4708222811671088 0.212890625 0.35278514588859416 
1  0.5166015625 0.34615384615384615 0.232421875 0.38461538461538464 0.5001435546875 0.32862201591511936 0.5995087890625 0.33585145888594164 0.5516005859375 0.4370623342175067 0.482400390625 0.4732082228116711 0.5445029296875 0.4852572944297082

**Comment by changhy666** [comment]
改下：
dataset.yaml里的names: [ 'face', 'body']
# number of classes
nc: 2

调试看下，报错再改










在 2023-04-13 11:25:27，"XhHello" ***@***.***> 写道：

检测人体不用改什么吧，标注的时候把人体标进去就行了，如果想区分人体和人脸算不同类别，顶多加个分类就好。 在 2023-04-13 10:15:13，"XhHello" @.> 写道： 请问如何修改yolov5-face， 变成可以检测人脸和关键点，又可以检测人体 您好，我想在检测人脸类和关键点的基础上，添加一个人体类检测（只要框），请问该修改代码里的哪些地方呢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.>

谢谢大佬指教，您说的“顶多加个分类”是啥意思啊，我现在的数据集就是两个类别（person、face）+关键点，相比于yolov5-face增加了一个person类，是否需要修改dataset.py的数据加载代码和loss.py中的损失函数，以及检测头的输出数据维度。
我的label文件格式是这样的，person类只有框，face类有框有关键点：
0 0.8037109375 0.4708222811671088 0.212890625 0.35278514588859416
1 0.5166015625 0.34615384615384615 0.232421875 0.38461538461538464 0.5001435546875 0.32862201591511936 0.5995087890625 0.33585145888594164 0.5516005859375 0.4370623342175067 0.482400390625 0.4732082228116711 0.5445029296875 0.4852572944297082

**Comment by XhHello** [comment]
> 首先需要加一个人体的类别的数据，5个关键点置为-1就好，因为目前代码的通用性不是太好，相关的地方比如输出shape要增加一个，切片位置也要改成你当前类别数，比如如果有三个类别那么输出就是conf1+box4+landm10+cls_score3
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2022年07月08日 18:10 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>、State ***@***.***> | | 主题 | Re: [deepcam-cn/yolov5-face] 多类别人脸，只能检测出来第一种人脸？ (#45) | 你好，我用这个代码跑3中类别人脸检测遇到了一点问题，多个类别训练完，跑检测脚本，只能预测出来第一个类别（人脸框，landm都正常），另外两个类别的人脸预测不出来，把过nms前，原始pred的tensor打印出来看，发现后两列被固定成0。然后检查了训练代码，发现另外两个类别的分类score和obj的score都是正常的，训练过程中的precision和recall指标都很低，不知道是不是跟nms超时10s有关。调试了很久找不到原因，可以帮忙分析下吗？谢谢。 hello, this is my question: train 3 class faces by this code, but when i run detect_face.py to pred a picture, only the 0 class can be success detected，the pred tensor of the other class faces always be 0.00000e+00. i checked the train.py, i also find the question, that is precision and recall is too low, but the pred tensor is ok in score of the other class face. 请问在哪里修改变成可以训练人脸，又可以检测人体 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>
请问您是如何将人体的类别的5个关键点置为-1的啊。如果想添加一个人体类，修改您说的这几个地方就可以了嘛。

**Comment by XhHello** [comment]
> 你可以看一下yolo.py里的67行左右y[..., [0,1,2,3,4,15]] = x[i][..., [0,1,2,3,4,15]].sigmoid() 这里作者手动写了需要做sigmoid的位置，其中最后的15是对第一类的计算，如果你想增加类别可以考虑加入16，17。 (我也调试了好久绝了。)

你好，我想在yoov5-face中增加一个人体类别检测(只有框，没有关键点)，请问我需要修改哪些地方的代码，谢谢。

> 



> 首先需要加一个人体的类别的数据，5个关键点置为-1就好，因为目前代码的通用性不是太好，相关的地方比如输出shape要增加一个，切片位置也要改成你当前类别数，比如如果有三个类别那么输出就是conf1+box4+landm10+cls_score3
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2022年07月08日 18:10 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>、State ***@***.***> | | 主题 | Re: [deepcam-cn/yolov5-face] 多类别人脸，只能检测出来第一种人脸？ (#45) | 你好，我用这个代码跑3中类别人脸检测遇到了一点问题，多个类别训练完，跑检测脚本，只能预测出来第一个类别（人脸框，landm都正常），另外两个类别的人脸预测不出来，把过nms前，原始pred的tensor打印出来看，发现后两列被固定成0。然后检查了训练代码，发现另外两个类别的分类score和obj的score都是正常的，训练过程中的precision和recall指标都很低，不知道是不是跟nms超时10s有关。调试了很久找不到原因，可以帮忙分析下吗？谢谢。 hello, this is my question: train 3 class faces by this code, but when i run detect_face.py to pred a picture, only the 0 class can be success detected，the pred tensor of the other class faces always be 0.00000e+00. i checked the train.py, i also find the question, that is precision and recall is too low, but the pred tensor is ok in score of the other class face. 请问在哪里修改变成可以训练人脸，又可以检测人体 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>
请问您说的“切片位置”是在哪个py文件中

**Comment by XhHello** [comment]
> 我在做这个改成二个类别识别的时候一直会有个 RuntimeError: The size of tensor a (48) must match the size of tensor b (51) at non-singleton dimension 0 错误，这是什么原因造成的呢

您好，请问您在改为二分类时，修改了代码中的哪些地方啊。

**Comment by mrmenand** [comment]
> > 请问如何修改yolov5-face， 变成可以检测人脸和关键点，又可以检测人体
> 
> 您好，我想在检测人脸类和关键点的基础上，添加一个人体类检测（只要框），请问该修改代码里的哪些地方呢

请问下你的问题解决了吗？我最近在碰到一个相似的问题？可以加个联系方式交流下吗？

**Comment by XhHello** [comment]
不好意思，刚看到这条信息，当时修改代码后有点问题，就没继续搞了，请问您实现了吗，qq:1757030891，欢迎您加好友指教




梧桐＆花叶雨
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "deepcam-cn/yolov5-face"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月23日(星期天) 中午11:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [deepcam-cn/yolov5-face] 多类别人脸，只能检测出来第一种人脸？ (#45)





   
请问如何修改yolov5-face， 变成可以检测人脸和关键点，又可以检测人体
  
您好，我想在检测人脸类和关键点的基础上，添加一个人体类检测（只要框），请问该修改代码里的哪些地方呢
  
请问下你的问题解决了吗？我最近在碰到一个相似的问题？可以加个联系方式交流下吗？
