### ISSUE TITLE
Regarding conversion of bounding box to yolo format in val2yolo.py

### ISSUE THREAD

**Issue by kartikeyporwal** [deepcam-cn/yolov5-face#54]
Hello!

Thanks for releasing such an amazing project.

In `val2yolo.py`, is there any specific reason that 1 pixel is being subtracted from `center_x` and `center_y` value in [line 19-20](https://github.com/deepcam-cn/yolov5-face/blob/0f88dcc2df80fd253da444d19f7271e2581303cf/data/val2yolo.py#L19-L20)?

Normally, only `x = (box[0] + box[1]) / 2.0` and `y = (box[2] + box[3]) / 2.0` should work as expected!

Also, why are coordinates for landmarks are set to -1 in val dataset?

Thanks

**Comment by changhy666** [comment]
-1 means no landmark info

**Comment by sunjian2015** [comment]
> Hello!
> 
> Thanks for releasing such an amazing project.
> 
> In `val2yolo.py`, is there any specific reason that 1 pixel is being subtracted from `center_x` and `center_y` value in [line 19-20](https://github.com/deepcam-cn/yolov5-face/blob/0f88dcc2df80fd253da444d19f7271e2581303cf/data/val2yolo.py#L19-L20)?
> 
> Normally, only `x = (box[0] + box[1]) / 2.0` and `y = (box[2] + box[3]) / 2.0` should work as expected!
> 
> Also, why are coordinates for landmarks are set to -1 in val dataset?
> 
> Thanks

I have the same question, do you have understand about 1 pixel is being subtracted from center_x and center_y?
