### ISSUE TITLE
 How to label data?

### ISSUE THREAD

**Issue by NguyenDinhTiem** [deepcam-cn/yolov5-face#57]
Hi, please help me, I don't understand your label format, can you explain it to me? What tool do you use to label it?

Your label:
![image](https://user-images.githubusercontent.com/59758186/131711176-533eebcb-a876-4026-a4c7-682718cf2bd6.png)

The yolov5 format I usually use:
![image](https://user-images.githubusercontent.com/59758186/131711611-4e67dccf-4a0d-48cc-bd90-bb159b7a60e8.png)

Thanks!

**Comment by changhy666** [comment]
you can find answer in the train2yolo.py.

**Comment by derronqi** [comment]
refer to retinaface
