### ISSUE TITLE
Question about the Mosaic augmentation

### ISSUE THREAD

**Issue by gkagkos** [deepcam-cn/yolov5-face#62]
First of all I would like to thank you for your great contribution and great work you have done. @derronqi 

I have a question regarding the mosaic augmentation.  Specifically, on your paper section **2.B (Contributions) 5th contrib.**, you mention that:

"_When small images are used, the Mosaic augmentation degrades the performance. However, when the small faces are ignored, it works well._" 

On the other hand though, on section **4.C (Data augmentation)** you mention that:

"_the Mosaic helps the mAP in the Hard dataset. As we explain before, the Mosaic has to work with the ignoring small faces, otherwise the performance degrades dramatically_." 

To my understanding the sentence "**_Mosaic has to work with the ignoring small faces_**" means that you need to take into consideration the small faces. This however, contradicts the contribution that you made. 

Most likely there something that I am missing but could you please help me solve this misunderstanding ? 
[Paper Link ](https://arxiv.org/abs/2105.12931)

**Comment by wjtan99** [comment]
It means that we ignore small faces and use Mosaic together.

**Comment by gkagkos** [comment]
Ok thanks for clarifying this.
