### ISSUE TITLE
提供的模型yolov5-face实验准确率

### ISSUE THREAD

**Issue by LiuSimon567** [deepcam-cn/yolov5-face#7]
您好，非常棒的工作，感谢您的分享，但是我使用您提供的模型yolov5s-face在单尺度最大边输入分辨率为1024的情况下，easy=94.4956，medium=93.2827，hard=87.9253，与您之前readme里提到的easy=95.4，medium=94.6，hard=88.2尚有差距，请问可能是由什么原因造成的呢？

**Comment by derronqi** [comment]
我是随便给的测试模型，后面会更新整个仓库，到时候给出新的模型

**Comment by LiuSimon567** [comment]
好的，期待您的更新。还想问一下，您训练时使用的就是目前代码里的超参吗？我使用a100在python=3.8.8 pytorch=1.7.1的环境下训练yolov5s并没有达到您之前readme里的结果。
