### ISSUE TITLE
关键点训练

### ISSUE THREAD

**Issue by eeric** [deepcam-cn/yolov5-face#8]
你的测试结果很棒。
请问关键点数据库用的是哪个？
我看wider face没有关键点标签，是吗？
另外，训练用的widerface.yaml，详细的图像数据与标签文件目录是怎么设置的？

**Comment by eeric** [comment]
关键点数据库从哪下载？谢谢

**Comment by derronqi** [comment]
数据使用的是widerface，关键点是insightface团队弄的，可以参考他们的retinaface仓库

**Comment by eeric** [comment]
好的，感谢！
https://github.com/sefaburakokcu/yolov3-facial-landmark-detection/tree/main/data/datasets/widerface
里面的label.txt有关键点，这个txt只是训练数据的吗，还是val也有标签？

**Comment by derronqi** [comment]
val不需要关键点了

**Comment by eeric** [comment]
在yolov5-face/data/widerface.yaml里面，val验证集怎么来的？
/ssd_1t/derron/yolov5-face/data/widerface/val

**Comment by eeric** [comment]
ok，thanks!
