### ISSUE TITLE
AttributeError: Can't get attribute 'SPPF' on <module 'models.common' from '**/yolov5-face-master/models/common.py'>

### ISSUE THREAD

**Issue by Zhao7601** [deepcam-cn/yolov5-face#84]
请问，SPPF是什么模块。

**Comment by Ilya-koala** [comment]
Hi, have you found a solution to this problem?

**Comment by wting861006** [comment]
models文件夹的comon.py缺少SPPF类，这个类在yolov5的v6.0版本里有，这要复制过来即可，这里直接把代码发出来

**Comment by emikulic** [comment]
From https://github.com/ultralytics/yolov5/blob/b3eaf5008bb8a34de481a6ef7ac8ba520d97b70e/models/common.py#L182 ?

**Comment by emikulic** [comment]
Don't run: `python3 detect_face.py --weights yolov5m.pt`

You need to manually download `yolov5m-face.pt` and run `python3 detect_face.py --weights yolov5m-face.pt`

The `download_weights.sh` script does the wrong thing IMO.

**Comment by HaithemH** [comment]
I have the sma problem as well. any solution!!!

**Comment by wjtan99** [comment]
Fixed by adding SPPF class into common.py
