### ISSUE TITLE
您好，我用detect_face.py进行人脸预测，却没有框，是什么原因？代码没改

### ISSUE THREAD

**Issue by lixiangMindSpore** [deepcam-cn/yolov5-face#87]
![result](https://user-images.githubusercontent.com/78945582/140032720-659dbefa-4842-435e-ad76-40600bfb9d97.jpg)

**Comment by derronqi** [comment]
这个是已经对齐后的人脸了，你可以尝试把deterct_face里面的检测大小改小点，例如320之类的看看。

**Comment by lixiangMindSpore** [comment]
> 这个是已经对齐后的人脸了，你可以尝试把deterct_face�里面的检测大小改小点，例如320之类的看看。

检测大小是在哪里改？方便列举一下代码吗？谢谢您

**Comment by derronqi** [comment]
img_size = 800，75行
