### ISSUE TITLE
YOLO5Face计算FLOPs的问题

### ISSUE THREAD

**Issue by lixiangMindSpore** [deepcam-cn/yolov5-face#88]
报错信息如下：
![image](https://user-images.githubusercontent.com/78945582/140274951-22f766a9-629c-41bc-875a-4493b07b90fe.png)

代码如下：
![image](https://user-images.githubusercontent.com/78945582/140274840-20226272-6584-4d9f-8208-11a04ef14aa2.png)

**Comment by derronqi** [comment]
yolo.py代码里面有
