### ISSUE TITLE
训练脚本

### ISSUE THREAD

**Issue by eeric** [deepcam-cn/yolov5-face#9]
单 gpu
python3 train.py
2个 gpu
python3 -m torch.distributed.launch --nproc_per_node 2 train.py
其它参数如 --batch-size 32 --data widerface.yaml --weights yolov5s.pt，是不是都是按train.py里面的默认设置吗？

**Comment by derronqi** [comment]
是的

**Comment by lycwgf** [comment]
batch size设置为32 ，但是训练的时候看起来实际batch size 是1，这个是需要修改什么地方吗
