### ISSUE TITLE
关于使用四个关键点训练的问题？

### ISSUE THREAD

**Issue by Hezhexi2002** [deepcam-cn/yolov5-face#91]
@derronqi ，大佬，我是一名大二学生，目前在我们学校robomaster战队里负责用神经网络识别装甲板，但是用yolo系列的话最后的bbox并不能很好的拟合装甲板的轮廓，导致我们后期在使用pnp进行姿态解算时会有很大误差，所以我想使用关键点检测的方法得到的bbox效果要好很多，就用装甲板的四个角点，就是我看您的这个项目应该能够实现，我想问一下就是需要改动哪些地方呢，loss和head就行了吗？

**Comment by derronqi** [comment]
看下代码，主要修改dataset.py和yolo.py

**Comment by Hezhexi2002** [comment]
> 看下代码，主要修改dataset.py和yolo.py

好的，谢谢大佬，就是现在我数据集的标签格式是类别和4个角点归一化后的x，y坐标，然后和标准的widerface数据集相比少了一个关键点，所以在这两个代码中删除多出来那个关键点的相关代码就行了吗？
