### ISSUE TITLE
Simple C++   cmake example

### ISSUE THREAD

**Issue by MyraBaba** [deepcam-cn/yolov5-face#94]
Hi,

Is there any simple cmak c++ example for inference with onnx converted models ? 

It would be very helpfull

PS: ncnn/android one is complicated

**Comment by derronqi** [comment]
check the readme, android demo and opencv dnn demo.

**Comment by MyraBaba** [comment]
@derronqi 
opencv dnn demo is for yolo5 object detection .

If there is a simple c++ example for : detecton, landrmark draws etc very helpfull

**Comment by derronqi** [comment]
https://github.com/hpc203/yolov5-face-landmarks-opencv-v2
